CHANGELOG.md, manifest.json, pages/pages.json, react/Menu.js
Fix 
Left items had a different format to the others. 
https://menu--storecomponents.myvtex.com/_v/menu
=> Fix format text of left menu item

CHANGELOG.md, react/Menu.js, react/__test__/__snapshots__/Menu.test.js.snap
- Hide menu on mobile mode
https://hidemenu--storecomponents.myvtex.com/
=> Update display to none in the mobile mode

CHANGELOG.md, manifest.json, react/Menu.js
Fix links default color
Previous link color is not that pretty
[Access the workspace](https://estacio--storecomponents.myvtex.com/)
=> Fix links default color

CHANGELOG.md, manifest.json, react/Menu.tsx
Use design tokens instead of tachyons hard coded colors and typography classes.
Its making this app more customizable through semantic css tokens.
[workspace](https://menudesigntokens--storecomponents.myvtex.com/)
=> Replace typography and color classes with design tokens

CHANGELOG.md, react/Menu.tsx
Potential solution to:
Fix #12 
Creates references to internal or external link
=> 12 menu links not rendering

CHANGELOG.md, manifest.json, react/Menu.tsx, react/constants/CSSClasses.js, react/menu.css
As title says
[Access this workspace](https://headercss--storecomponents.myvtex.com/)
=> Add support to css modules

CHANGELOG.md, manifest.json, react/Menu.tsx
=> [humanelement] Link rendering to include whether it is internal/external

CHANGELOG.md, manifest.json, react/__mocks__/vtex.store-components.tsx, react/index.tsx, react/typings/vtex.store-components.d.ts
As the title says
Ecowater account
=> Add page padding in menu-link

CHANGELOG.md, manifest.json
=> Release v2.6.4

.vtexignore, CHANGELOG.md, README.md, react/.babelrc, react/.prettierrc, react/__mocks__/vtex.store-components.tsx, react/__test__/Menu.test.js, react/__test__/__snapshots__/Menu.test.js.snap, react/index.tsx, react/package.json, react/testUtils/setupTests.js, react/testUtils/test-utils.js, react/yarn.lock
=> Add React testing library and Add Snapshot tests

CHANGELOG.md, manifest.json, react/.prettierrc, react/Menu.tsx, react/MenuItem.tsx, react/Submenu.tsx, react/components/CategoryItem.tsx, react/components/CustomItem.tsx, react/components/Item.tsx, react/components/MenuContext.tsx, react/components/StyledLink.tsx, react/package.json, react/tsconfig.json, react/typings/global.d.ts, react/yarn.lock
Add an option to set a Menu title.
This will solve category menus, footer menu, and sidebar menu.
Add the prop title to your `menu` or `second-level-menu` in `blocks.json`:
```json
"unstable--second-level-menu#foo": {
"props": {
"orientation": "vertical",
"title": {
"id": "unstable--menu-item-1",
"type": "category",
"iconId": null,
"highlight": false,
"itemProps": {
"categoryId": 1
}
}
},
"children": [
"unstable--second-level-menu-item#hats",
"unstable--second-level-menu-item#custom"
]
},
```
Development workspace:
https://breno--storecomponents.myvtex.com/?disableUserLand
Footer | Header
---|---
=> Menu Title

CHANGELOG.md, manifest.json, store/interfaces.json
Allow infocard on submenu and submenu-col
=> Allow infocard on submenu and submenu-col

CHANGELOG.md, manifest.json, react/Menu.tsx, react/MenuItem.tsx, react/Submenu.tsx, react/__mocks__/vtex.native-types/index.tsx, react/components/CustomItem.tsx, react/components/Item.tsx, react/typings/vtex.native-types.d.ts, store/contentSchemas.json, store/interfaces.json
- Add support to new content types through `contentSchemas.json`, i18n and dynamic form.
Edit menu and menu-items at: 
https://jey--alssports.myvtex.com/admin/cms/storefront
=> Feature content types

react/__tests__/StyledLink.test.tsx
=> Fix style linked test

CHANGELOG.md, react/components/StyledLink.tsx
=> Fix iconId DOM warning from Link

CHANGELOG.md
Enable lazy evaluation of menu entrypoints
Performance! :developers:
=> Enable lazy evaluation of menu entrypoints

README.md
As the title says, the Menu README was rewritten.
=> New Menu README

CHANGELOG.md, react/components/Item.tsx
Fix menu item behavior.
Menu item not working as intended.
[Storecomponents workspace](https://fixmenuitem--storecomponents.myvtex.com/)
PS: I didn't thoroughly test this on other accounts, just on the account that raised the issue and storecomponents.
=> Fix item props not being applied

CHANGELOG.md, manifest.json, store/interfaces.json
Allow rich-text inside submenu. Also added other components as allowed.
1. Open https://breno--storecomponents.myvtex.com/
2. Open the submenu "Clothing"
3. Check the richness of the text
=> Allow rich-text inside submenu

.all-contributorsrc, .github/CODEOWNERS
This automated pull request aims to:
- Add `all-contributors` to the project.
- Add `CODEOWNERS` with mentions to the store-framework dev team and the tech-writers team for `docs` changes.
=> Add all-contributors and codeowners

CHANGELOG.md, docs/README.md, react/Menu.tsx, react/package.json, react/yarn.lock
When creating a new Menu having their menu items as props the component breaks since the object `itemProps` doesn't exist yet.
Open
https://breno--equishopper.myvtex.com/admin/cms/site-editor/ovation/v2
Edit Related Searches > Related search link
Create new Item, it shouldn't break
=> Avoid breaking when itemProps is null

CHANGELOG.md, react/components/CategoryItem.tsx, react/components/CategoryMenu.tsx
https://fidelis--paguemenos.myvtex.com/
=> avoid breaking when doing category query with null id

CHANGELOG.md, docs/README.md, react/Submenu.tsx
Make it possible to create animation effects with the submenu opening and closing.
https://department--tfbsmy.myvtex.com/feminino
=> Add CSS handles modifiers when submenu is open or closed
