vtex-apps/menu

- CHANGELOG.md
- react/Menu.js
- react/__test__/__snapshots__/Menu.test.js.snap
- react/global.css
- Remove border-bottom of menu.
https://claudivan--storecomponents.myvtex.com/make-b--brilho-labial-star-lip-7ml-166starlipbril/p
> Remove menu border bottom

- CHANGELOG.md
- manifest.json
- react/Menu.tsx
As the title says.
The component should be not rendered if there is no links to be displayed.
To test this new feature you need to access the storefront and try to add and remove links from the menu in order to see that the component will not be rendered when there is no links.
[Click here to accces the storefront](https://menu--storecomponents.myvtex.com/admin/cms/storefront)
> Render nothing if there is no links to be displayed

- CHANGELOG.md
- manifest.json
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/components/Item.tsx
Add missing translation strings.
Fix Portuguese and Spanish CMS translations.
Check the CMS here:
https://breno--storecomponents.myvtexdev.com/admin/cms/storefront
> Add missing translation strings

- CHANGELOG.md
- manifest.json
- react/components/StyledLink.tsx
Removes warnings
```
React does not recognize the `iconId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
React does not recognize the `treePath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `treepath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
This second one I thought was happening because of render-runtime, but it is (correctly) not passing down `treePath`. It's the `useTreePath` in `useSubmenuImplementation` that's the problem. I don't have enough context, but this probably …
> Fix incorrect prop passing

- CHANGELOG.md
- manifest.json
- react/Menu.tsx
Send only the message `id` to the menu component schema.
Menu content editor on admin exploding when opened.
Edit menu content on admin.
> Fix menu messages

- CHANGELOG.md
- manifest.json
- react/Menu.css
- react/Menu.tsx
- react/MenuItem.css
- react/MenuItem.tsx
- react/Submenu.css
- react/Submenu.tsx
- react/SubmenuAccordion.css
- react/SubmenuAccordion.tsx
- react/package.json
- react/yarn.lock
To increment on menu and their submenus a classes, to make more easy insert a different styles on anothers areas of website.
Without this, we can't use menu on differents areas with different styles, mainly get subitens. Was very hard to make a layout without this option. 
https://giovanatexas--qdlab.myvtex.com/
> Insert blockClass import on files of Menu

- CHANGELOG.md
- store/interfaces.json
To make it able to put an image inside a submenu
Image component wasn't allowed previously within a submenu
Insert an image as child from a sub-menu
> Allows image component to be placed within sub-menu

- CHANGELOG.md
- react/components/CustomItem.tsx
Get the correct href for menu item.
The href for menu items were not being translated properly, so the generated url was something like `https://adb-acessorios-para-patchwork.mygocommerce.com/store/menu-item.itemProps.href.7ziR3MKai6EeRkWLowgboH~g7KzNCKjvYMqppSvaDyoZk`. The href must be an IO Message for friendly href purposes. 
https://augusto--adb-acessorios-para-patchwork.mygocommerce.com/
> Fix href IO message

- CHANGELOG.md
- react/components/StyledLink.tsx
Fix [this](https://github.com/vtex-apps/store-discussion/issues/81)
[Workspace](https://iaronaraujo--storecomponents.myvtex.com)
Click on the `news` button in the footer and you should be redirected to Google
> Fixed styledLink's href when it had a `?`

- CHANGELOG.md
- react/MenuItem.tsx
Prevents submenu from rendering when it's not active, to improve rendering performance.
Before:
After:
https://lbebber3--alssports.myvtex.com/
> Prevent submenu rendering

- CHANGELOG.md
- react/graphql/categoryWithChildren.graphql
There were two GraphQL queries with the same name `category`.
This should fix build.
[Workspace](https://minicart--storecomponents.myvtex.com/)
> Rename duplicate `category` query to `categoryWithChildren`

- CHANGELOG.md
- store/contentSchemas.json
in menu-item the href was being translated when it shouldn't, the urls will not be translated when you change locale, only when you change binding and this will be handled somewhere else.
https://menu--storecomponents.myvtex.com/?cultureInfo=ja-jp
menu-items should not have translated href
> make href a string

- CHANGELOG.md
- react/components/CustomItem.tsx
Em alguns casos ainda aparecia a url traduzida
> dont pass href to formatIOMessage to avoid translating

- CHANGELOG.md
- docs/README.md
- react/Submenu.tsx
Add a `submenuWrapper` handle.
Missing handle on one of submenu's elements.
Open https://chris--storecomponents.myvtex.com/ and check if the `submenuContainer` direct children have a `submenuWrapper` class.
> Add submenuWrapper css handle

- CHANGELOG.md
- docs/README.md
- manifest.json
- react/MenuItem.tsx
- store/interfaces.json
Update `menu-item` interface to `composition: children`, which enables blocks to be passed through `children`.
Enables users to further customize their menus. Also, this should enable them to use the `drawer` block inside a `menu-item` to achieve something such as: 
Open the following workspace on mobile and see that there is a `drawer` inside a `menu-item`.
[Workspace](https://menuchildren--storecomponents.myvtex.com/apparel---accessories/)
> Make `menu-item` render children blocks

- CHANGELOG.md
- docs/README.md
- react/MenuItem.tsx
Allowing menu item customization when submenu is open or closed
[Workspace](https://menuitemcsshandles--tokstokio.myvtex.com/)
> Add CSS handle to menu item when submenu is open or closed

- CHANGELOG.md
- messages/context.json
- messages/en.json
- react/components/StyledLink.tsx
- store/contentSchemas.json
Be able to edit the SVG icon from Site Editor. Currently, to change an icon it is necessary to do it from the theme app.
This is useful for not repeating different `menu` or `menu-item` blocks in the .jsonc files just to change the icon, instead, it is possible to have only one general block and do all customization from Site Editor. This will also make site maintenance easier.
[Workspace / Site Editor](https://featuremenuiconsfromsiteeditor--martimxlite.myvtex.com)
1. Use Mobile view
2. Click on hamburguer menu icon
3. Select any menu item (menu-item or menu)
4. Edit the menu item
5. Change the id of svg icon (Icon Props: ID) by `svgIcon-house`
> SVG icon from Site Editor

- CHANGELOG.md
- store/contentSchemas.json
As the title says. It shouldn't have been removed in this [PR](https://github.com/vtex-apps/menu/pull/149).
Check if the category Id field appears in the site editor of this [workspace](https://laricia--vasoecor.myvtex.com/admin/cms/site-editor).
Before - without the field:
After - with the field:
> Add back the categoryId to site editor

- .husky/pre-commit
- CHANGELOG.md
- package.json
- yarn.lock
We are updating dependencies to solve some security issues alerted by dependabot.
Two (https://github.com/vtex-apps/menu/security/dependabot/13 & https://github.com/vtex-apps/menu/security/dependabot/26) of these issues is regarding `semver-regex`, but `dependabot` couldn't update it automatically.
In the new husky version `semver-regex` isn't used anymore, so I did the [migration from v4](https://github.com/typicode/husky/releases/tag/v6.0.0) and updated husky to v8.
Nothing should've changed: [workspace](https://laricia2--storecomponents.myvtex.com/)
> Chore: Update husky

- CHANGELOG.md
- react/MenuItem.tsx
When we have a item hovered (active) and move the mouse to another element very fast, sometimes the `isActive` state does not change to false, because in evaluation `onMountBehaviorFlag==="close"` `onMountBehaviorFlag` sometimes comes to undefined
[Workspace](https://ycl--poccarrefourarg.myvtex.com/)
before:
https://user-images.githubusercontent.com/40153830/226982476-ef39c350-918c-49e5-b204-a7e3ccb902d1.mp4
---
after:
https://user-images.githubusercontent.com/40153830/226982492-577a66b1-d4c8-4458-a88a-1e1beae6e135.mp4
> fix: deactivate item when is not open
